In [1]:
import pandas as pd
import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup as bs

In [326]:
#Create new web browser window
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

In [327]:
#Pull up the desired website to scrape
page_url = 'https://infrastructurereportcard.org/state-item/wisconsin/'
driver.get(page_url)

In [328]:
#Create the soup
soup = bs(driver.page_source, "html.parser")

In [329]:
#Create a list of column headers
table_headers = ['Infrastructure', 'Grade']

In [330]:
#Scrape the content from the website
content = []
for x in soup.find_all('div', class_='e-flex'):
    div_tags = x.find_all('div', class_='e-grade')
    span_tags = x.find_all('span')
    span_val = [y.text for y in span_tags]
    content.append(span_val)
content

[['Aviation', 'C+'],
 ['Bridges', 'C+'],
 ['Dams', 'C+'],
 ['Drinking Water', 'C-'],
 ['Energy', 'B'],
 ['Hazardous Waste', 'B-'],
 ['Inland Waterways', 'C-'],
 ['Ports', 'C+'],
 ['Roads', 'D+'],
 ['Solid Waste', 'B-'],
 ['Stormwater', 'C'],
 ['Transit', 'D+'],
 ['Wastewater', 'C-']]

In [331]:
#Create a dataframe of the content and column headers
infrastructure_df = pd.DataFrame(content, columns = table_headers)
infrastructure_df

      Infrastructure Grade
0           Aviation    C+
1            Bridges    C+
2               Dams    C+
3     Drinking Water    C-
4             Energy     B
5    Hazardous Waste    B-
6   Inland Waterways    C-
7              Ports    C+
8              Roads    D+
9        Solid Waste    B-
10        Stormwater     C
11           Transit    D+
12        Wastewater    C-

In [332]:
#Create a new column for the state names
infrastructure_df.insert(0, 'State', ['Wisconsin','Wisconsin','Wisconsin','Wisconsin','Wisconsin','Wisconsin','Wisconsin','Wisconsin','Wisconsin','Wisconsin','Wisconsin','Wisconsin','Wisconsin'])
infrastructure_df

        State    Infrastructure Grade
0   Wisconsin          Aviation    C+
1   Wisconsin           Bridges    C+
2   Wisconsin              Dams    C+
3   Wisconsin    Drinking Water    C-
4   Wisconsin            Energy     B
5   Wisconsin   Hazardous Waste    B-
6   Wisconsin  Inland Waterways    C-
7   Wisconsin             Ports    C+
8   Wisconsin             Roads    D+
9   Wisconsin       Solid Waste    B-
10  Wisconsin        Stormwater     C
11  Wisconsin           Transit    D+
12  Wisconsin        Wastewater    C-

In [333]:
#Create a csv file for each state's information
infrastructure_df.to_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\wisconsin_infrastructure_data.csv", index=False)

In [335]:
#Read in all the state files
alabama = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\alabama_infrastructure_data.csv")
alaska = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\alaska_infrastructure_data.csv")
arizona = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\arizona_infrastructure_data.csv")
california = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\california_infrastructure_data.csv")
colorado = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\colorado_infrastructure_data.csv")
connecticut = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\connecticut_infrastructure_data.csv")
dc = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\dc_infrastructure_data.csv")
florida = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\florida_infrastructure_data.csv")
georgia = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\georgia_infrastructure_data.csv")
hawaii = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\hawaii_infrastructure_data.csv")
idaho = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\idaho_infrastructure_data.csv")
illinois = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\illinois_infrastructure_data.csv")
iowa = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\iowa_infrastructure_data.csv")
kansas = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\kansas_infrastructure_data.csv")
kentucky = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\kentucky_infrastructure_data.csv")
louisiana = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\louisiana_infrastructure_data.csv")
maine = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\maine_infrastructure_data.csv")
maryland = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\maryland_infrastructure_data.csv")
michigan = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\michigan_infrastructure_data.csv")
minnesota = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\minnesota_infrastructure_data.csv")
mississippi = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\mississippi_infrastructure_data.csv")
missouri = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\missouri_infrastructure_data.csv")
montana = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\montana_infrastructure_data.csv")
nevada = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\nevada_infrastructure_data.csv")
new_hampshire = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\new_hampshire_infrastructure_data.csv")
new_york = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\new_york_infrastructure_data.csv")
north_dakota = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\north_dakota_infrastructure_data.csv")
ohio = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\ohio_infrastructure_data.csv")
oregon = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\oregon_infrastructure_data.csv")
pennsylvania = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\pennsylvania_infrastructure_data.csv")
rhode_island = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\rhode_island_infrastructure_data.csv")
south_carolina = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\south_carolina_infrastructure_data.csv")
texas = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\texas_infrastructure_data.csv")
utah = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\utah_infrastructure_data.csv")
vermont = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\vermont_infrastructure_data.csv")
washington = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\washington_infrastructure_data.csv")
west_virginia = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\west_virginia_infrastructure_data.csv")
wisconsin = pd.read_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\wisconsin_infrastructure_data.csv")

In [340]:
#Combine all state files
infrastructure_report_card_df = pd.concat([alabama,alaska,arizona,california,colorado,connecticut,dc,florida,georgia,hawaii,idaho,illinois,iowa,kansas,kentucky,louisiana,maine,maryland,michigan,minnesota,mississippi,missouri,montana,nevada,new_hampshire,new_york,north_dakota,ohio,oregon,pennsylvania,rhode_island,south_carolina,texas,utah,vermont,washington,west_virginia,wisconsin], axis=0, ignore_index=True)
infrastructure_report_card_df

         State  Infrastructure Grade
0      Alabama        Aviation     C
1      Alabama         Bridges    C+
2      Alabama            Dams     ?
3      Alabama  Drinking Water    C-
4      Alabama          Energy     B
..         ...             ...   ...
417  Wisconsin           Roads    D+
418  Wisconsin     Solid Waste    B-
419  Wisconsin      Stormwater     C
420  Wisconsin         Transit    D+
421  Wisconsin      Wastewater    C-

[422 rows x 3 columns]

In [342]:
#export combined file as csv
infrastructure_report_card_df.to_csv(r"C:\Users\Nathan\Documents\Python Projects\Mcadams Projects\Best Locations\data\state_infrastructure_report_card_data.csv", index=False)